baseURL = 'https://puthujjana.github.io/theragatha/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-book"

[params]
  BookToC = true
  BookMenuBundle = '/menu'
  BookSection = 'docs'
  BookRepo = ''
  BookSearch = false
