baseURL = 'https://theragatha.github.io'
languageCode = 'en-us'
title = 'Therāgātha'
theme = "hugo-book"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  BookToC = true
  BookMenuBundle = '/menu'
  BookSection = '*'
  BookRepo = ''
  BookSearch = false
  tocLevels = 2 # show only ## and ### headings
  showMainMenu = true
  [[params.translators]]
    name = "Bhikkhu Sujato"
    key = "sujato"
  [[params.translators]]
    name = "Ṭhānissaro Bhikkhu"
    key = "thanissaro"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    title = "Theragāthā"

  [languages.es]
    languageName = "Español"
    weight = 2
    contentDir = "content/es"
    title = "Theragāthā"

[menu]

  [[menu.after]]
  name = "→ Report Error"
  url = "https://forms.gle/hnsM4pMcEHzHVeKa9"
  weight = 999
